### ISSUE TITLE
Retrofit error

### ISSUE THREAD

**Issue by anaktas** [xively/xively-mobile-sdk-android#4]
I'm experiencing an issue while trying to authenticate to the Xively broker. Below is the stack trace:  

```
12-22 18:28:13.515 21540-21853/com.traegergrills.app D/Retrofit: java.lang.IllegalArgumentException: LoginUser.a: HTTP method annotation is required (e.g., @GET, @POST, etc.).
                                                                     at retrofit.RestMethodInfo.a(RestMethodInfo.java:107)
                                                                     at retrofit.RestMethodInfo.b(RestMethodInfo.java:179)
                                                                     at retrofit.RestMethodInfo.a(RestMethodInfo.java:117)
                                                                     at retrofit.RestAdapter$RestHandler.a(RestAdapter.java:292)
                                                                     at retrofit.RestAdapter$RestHandler.a(RestAdapter.java:220)
                                                                     at retrofit.RestAdapter$RestHandler$2.a(RestAdapter.java:278)
                                                                     at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at retrofit.Platform$Android$2$1.run(Platform.java:142)
                                                                     at java.lang.Thread.run(Thread.java:818)
12-22 18:28:13.515 21540-21853/com.traegergrills.app D/Retrofit: ---- END ERROR
                                                                 
                                                                 [ 12-22 18:28:13.523 21540:21540 I/         ]
                                                                 [XiAuthentication] Authentication failed: retrofit.RetrofitError: LoginUser.a: HTTP method annotation is required (e.g., @GET, @POST, etc.).
```

FYI, this issue occurs only when I'm running the zipped apk. It works fine when I'm debugging the app.

**Comment by srayhunter** [comment]
@anaktas this is an error with how proguard is handling the merging of the aar file into the project.
